version: "3.8"
services:
  typo3-local:
    env_file: environments/develop/.env
    image: unicorn-developers/typo3:9.5
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-typo3
    links:
      - mariadb10.1
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    environment:
      TYPO3_CONTEXT: ${TYPO3_CONTEXT}
      DOCKER_HOST: "unix:///var/run/docker.sock"
    privileged: true
    user: root

  build-apache2-php7.4:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    image: ${NAMESPACE}/${COMPOSE_PROJECT_NAME}-typo3:base
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-webserver
    volumes:
      - .:/var/www/html
      # - ./environments/build/php:/usr/local/etc/php
      - ./environments/build/sites-enabled:/etc/${WEBSERVER}/sites-enabled
      - ./environments/build/cron.d:/etc/cron.d
    links:
      - mariadb10.1
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    environment:
      TYPO3_CONTEXT: ${TYPO3_CONTEXT}
      DOCKER_HOST: "unix:///var/run/docker.sock"
    privileged: true
    user: root

  mariadb10.1:
    image: mariadb:10.1
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-database
    # add this line if you want to auto load your database
    # volumes:
    #   - ./environments/local/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${TYPO3__DB__Connections__Default__dbname}
      MYSQL_USER: ${TYPO3__DB__Connections__Default__user}
      MYSQL_PASSWORD: ${TYPO3__DB__Connections__Default__password}
    ports:
      - "3306:3306"

  mailcatcher:
    image: sj26/mailcatcher
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-mailcatcher
    ports:
      - "1080:1080"
