version: "3.8"
services:
  webserver:
    build:
      context: environments/local
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    container_name: apache2-php-7.4
    volumes:
      - .:/var/www/html
      # - ./environments/local/server/development.conf:/etc/nginx/conf.d/default.conf
      # - ./environments/local/php:/usr/local/etc/php
      - ./environments/local/sites-enabled:/etc/apache2/sites-enabled
      - ./environments/local/cron.d:/etc/cron.d
    links:
      - database
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    environment:
      TYPO3_CONTEXT: ${TYPO3_CONTEXT}
      DOCKER_HOST: "unix:///var/run/docker.sock"
    privileged: true
    user: root

  database:
    image: mariadb:10.1
    container_name: mariadb-10.1
    # add this line if you want to auto load your database
    # volumes:
    #   - ./environments/local/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${TYPO3__DB__Connections__Default__dbname}
      MYSQL_USER: ${TYPO3__DB__Connections__Default__user}
      MYSQL_PASSWORD: ${TYPO3__DB__Connections__Default__password}
    ports:
      - "3306:3306"

  mailcatcher:
    image: sj26/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
