version: "3.8"
services:
  typo3-develop-environment:
    env_file: environments/develop/.env
    image: docker.pkg.github.com/michagrandel/website-setup/website-base:apache
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-typo3
    links:
      - mariadb10.1-dev
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./environments/build/sites-enabled:/etc/apache2/sites-enabled
      - ./environments/build/cron.d:/etc/cron.d
      - ./environments/build/cron.d:/etc/cron.d
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    privileged: true
    user: root

  build-apache2-php7.4:
    env_file: environments/build/.env
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    image: ${NAMESPACE}/${COMPOSE_PROJECT_NAME}-typo3:base
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-base
    links:
      - mariadb10.1
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    privileged: true
    user: root

  mariadb10.1-dev:
    image: mariadb:10.1
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-database
    env_file: environments/develop/.env
    environment:
      MYSQL_ROOT_PASSWORD: xkLWXVbJAJu09RWZPtB3jNQpN
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  mariadb10.1:
    image: mariadb:10.1
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-database
    env_file: environments/build/.env
    environment:
      MYSQL_ROOT_PASSWORD: mG30sDAb2VcXlp7WYjvpNg3Ro
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  mailcatcher:
    image: sj26/mailcatcher
    container_name: ${NAMESPACE}-${COMPOSE_PROJECT_NAME}-mailcatcher
    ports:
      - "1080:1080"
