name: Build and push docker image

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  # job to build and push a docker image
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build develop docker image and tag it accordingly for later upload
      - name: Build develop-image
        if: ${{ endsWith(github.ref, 'develop') }}
        env:
          REPOSITORY: ${{ github.repository }}
        run: docker build -f Dockerfile.build -t docker.pkg.github.com/$REPOSITORY/website-base:apache-dev .

      # Build master docker image and tag it accordingly for later upload
      - name: Build release-image
        if: ${{ endsWith(github.ref, 'master') }}
        env:
          REPOSITORY: ${{ github.repository }}
        run: docker build -f Dockerfile.build -t docker.pkg.github.com/$REPOSITORY/website-base:apache .

      # Login to docker
      - name: Login docker
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com --username michagrandel --password $TOKEN

      # Push develop docker image to github
      - name: Push develop-image
        if: ${{ endsWith(github.ref, 'develop') }}
        env:
          REPOSITORY: ${{ github.repository }}
        run: docker push docker.pkg.github.com/${{ github.repository }}/website-base:apache-dev

      # Push master docker image to github
      - name: Push release-image
        if: ${{ endsWith(github.ref, 'master') }}
        env:
          REPOSITORY: ${{ github.repository }}
        run: docker push docker.pkg.github.com/${{ github.repository }}/website-base:apache
