name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and tag docker image
        run: |
          docker build -f Dockerfile.build -t docker.pkg.github.com/${{ github.repository }}/website-base .
      # docker save -o typo3.tar typo3:base

      # Runs a set of commands using the runners shell
      - name: Login docker
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com --username michagrandel --password $TOKEN

